trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  browser: ${{ variables['inputs.browser'] }}
  headless: ${{ variables['inputs.headless'] }}
  tracing: ${{ variables['inputs.tracing'] }}

steps:
  - checkout: self

  - task: Cache@2
    displayName: Cache Maven dependencies
    inputs:
      key: 'maven | "$(Agent.OS)" | **/pom.xml'
      restoreKeys: 'maven | "$(Agent.OS)" |'
      path: '$(Agent.HomeDirectory)/.m2/repository'
      cacheHitVar: 'MavenCacheHit'
    continueOnError: true

  - task: UseJavaVersion@1
    displayName: Set up JDK 11
    inputs:
      versionSpec: '11'
      architecture: 'x64'
      jdkSourceOption: 'PreInstalled'

  - task: Maven@3
    displayName: Run tests
    inputs:
      mavenPomFile: 'pom.xml'
      options: '-Dbrowser=$(browser) -Dheadless=$(headless) -Dtracing=$(tracing)'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '11'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'

  - task: PublishTestResults@2
    displayName: Publish test results
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      searchFolder: '$(System.DefaultWorkingDirectory)'