trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: browserSelection
    type: string
    default: 'chrome'
    values:
      - chrome
      - firefox
      - webkit

  - name: headless
    type: string
    default: 'true'
    values:
      - true
      - false

  - name: tracing
    type: string
    default: 'false'
    values:
      - true
      - false

schedules:
  - cron: '0 0 * * *'
    displayName: Daily midnight build
    branches:
      include:
        - main

steps:
  - task: MavenAuthenticate@0
    inputs:
      artifactsFeeds: 'mavenFeed'
      workingDirectory: '$(System.DefaultWorkingDirectory)'

  - script: |
      echo 'Browser '${{ parameters.browserSelection }}  
      echo 'Headless '${{ parameters.headless }}
      echo 'Tracing '${{ parameters.tracing }}  

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      options: '-Dbrowser=${{ parameters.browserSelection }}  -Dheadless=${{ parameters.headless }} -Dtracing=${{ parameters.tracing }}'
      javaHomeOption: 'JDKVersion'
      jdkVersionOption: '11'
      publishJUnitResults: true
      testResultsFiles: '**/surefire-reports/TEST-*.xml'

  - task: PublishTestResults@2
    inputs:
      testResultsFormat: 'JUnit'
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      testRunTitle: 'JUnit tests'
      failTaskOnFailedTests: true

  - task: MavenAuthenticate@0
    inputs:
      artifactsFeeds: 'mavenFeed'
      workingDirectory: '$(System.DefaultWorkingDirectory)'

  - task: PublishBuildArtifacts@1
    inputs:
      artifactName: 'drop'
      pathtoPublish: '$(System.DefaultWorkingDirectory)/target/surefire-reports'
